import { ArtmovementsEnum } from "@/model/enums/ArtmovementsEnum";
import { AuthorsEnum } from "@/model/enums/AuthorsEnum";

const ArtObject = [
  {
    title: "La Gioconda",
    author: AuthorsEnum.LEONARDO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "/assets/images/La_Gioconda,_Leonardo_Da_Vinci.jpg",
  },
  {
    title: "Starry Night",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "/assets/images/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
  },
  {
    title: "The Birth of Venus",
    author: AuthorsEnum.BOTTICELLI,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "/assets/images/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
  },
  {
    title: "Girl with a Pearl Earring",
    author: AuthorsEnum.VERMEER,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "/assets/images/1665_Girl_with_a_Pearl_Earring.jpg",
  },
  {
    title: "The Last Supper",
    author: AuthorsEnum.LEONARDO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "/assets/images/The_Last_Supper_-_Leonardo_Da_Vinci_-_High_Resolution_32x16.jpg",
  },
  {
    title: "The Kiss",
    author: AuthorsEnum.KLIMT,
    artmovement: ArtmovementsEnum.ART_NOUVEAU,
    link: "/assets/images/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
  },
  {
    title: "Las Meninas",
    author: AuthorsEnum.VELASQUEZ,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "/assets/images/Las_Meninas,_by_Diego_Velázquez,_from_Prado_in_Google_Earth.jpg",
  },
  {
    title: "American Gothic",
    author: AuthorsEnum.WOOD,
    artmovement: ArtmovementsEnum.MODERN,
    link: "/assets/images/Grant_DeVolson_Wood_-_American_Gothic.jpg",
  },
  {
    title: "A Sunday Afternoon on the Island of La Grande Jatte",
    author: AuthorsEnum.SEURAT,
    artmovement: ArtmovementsEnum.POINTILLISM,
    link: "/assets/images/640px-Georges_Seurat_-_Un_dimanche_après-midi_à_l'Île_de_la_Grande_Jatte_v2.jpeg",
  },
  {
    title: "Guernica",
    author: AuthorsEnum.PICASSO,
    artmovement: ArtmovementsEnum.CUBISM,
    link: "/assets/images/PicassoGuernica.jpg",
  },
  {
    title: "The Night Watch",
    author: AuthorsEnum.REMBRANDT,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "/assets/images/640px-The_Night_Watch_-_Rembrandt_Harmenszoon_van_Rijn.png",
  },
  {
    title: "Café Terrace at Night",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Van_Gogh_-_Terrasse_des_Caf%C3%A9s_an_der_Place_du_Forum_in_Arles_am_Abend1.jpeg/640px-Van_Gogh_-_Terrasse_des_Caf%C3%A9s_an_der_Place_du_Forum_in_Arles_am_Abend1.jpeg",
  },
  {
    title: "Whistler's Mother",
    author: AuthorsEnum.WHISTLER,
    artmovement: ArtmovementsEnum.TONALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Whistlers_Mother_high_res.jpg/640px-Whistlers_Mother_high_res.jpg",
  },
  {
    title: "The Sleeping Gypsy",
    author: AuthorsEnum.ROUSSEAU,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/La_Boh%C3%A9mienne_endormie.jpg/640px-La_Boh%C3%A9mienne_endormie.jpg",
  },
  {
    title: "Bal du moulin de la Galette",
    author: AuthorsEnum.RENOIR,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://cdn.shopify.com/s/files/1/1771/4067/files/Bal_du_moulin_de_la_Galette_by_Pierre-Auguste_Renoir_d1c9f4e7-113b-43b7-9426-6e58eaa4cf98_large.jpg?v=1571688399",
  },
  {
    title: "Impression",
    author: AuthorsEnum.MONET,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/640px-Monet_-_Impression%2C_Sunrise.jpg",
  },
  {
    title: "The Third of May 1808",
    author: AuthorsEnum.GOYA,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg/640px-El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg",
  },
  {
    title: "Liberty Leading the People",
    author: AuthorsEnum.DELACROIX,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Eug%C3%A8ne_Delacroix_-_Liberty_Leading_the_People_%2828th_July_1830%29_-_WGA6177.jpg/640px-Eug%C3%A8ne_Delacroix_-_Liberty_Leading_the_People_%2828th_July_1830%29_-_WGA6177.jpg",
  },
  {
    title: "The Luncheon on the Grass",
    author: AuthorsEnum.MANET,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg/640px-Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg",
  },
  {
    title: "Lady with an Ermine",
    author: AuthorsEnum.LEONARDO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Lady_with_an_Ermine_-_Leonardo_da_Vinci_-_Google_Art_Project.jpg/640px-Lady_with_an_Ermine_-_Leonardo_da_Vinci_-_Google_Art_Project.jpg",
  },
  {
    title: "The Raft of the Medusa",
    author: AuthorsEnum.GERICAULT,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg/640px-JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg",
  },
  {
    title: "Nighthawks",
    author: AuthorsEnum.HOPPER,
    artmovement: ArtmovementsEnum.MODERN,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/640px-Nighthawks_by_Edward_Hopper_1942.jpg",
  },
  {
    title: "Luncheon of the Boating Party",
    author: AuthorsEnum.RENOIR,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg/640px-Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg",
  },
  {
    title: "Napoleon Crossing the Alps",
    author: AuthorsEnum.DAVID,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Napoleon_at_the_Great_St._Bernard_-_Jacques-Louis_David_-_Google_Cultural_Institute.jpg/640px-Napoleon_at_the_Great_St._Bernard_-_Jacques-Louis_David_-_Google_Cultural_Institute.jpg",
  },
  {
    title: "View of Toledo",
    author: AuthorsEnum.GRECO,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/El_Greco_-_View_of_Toledo_-_Google_Art_Project.jpg/640px-El_Greco_-_View_of_Toledo_-_Google_Art_Project.jpg",
  },
  {
    title: "The Storm on the Sea of Galilee",
    author: AuthorsEnum.REMBRANDT,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg/640px-Rembrandt_Christ_in_the_Storm_on_the_Lake_of_Galilee.jpg",
  },
  {
    title: "The Harvesters",
    author: AuthorsEnum.BRUEGHEL_ELDER,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/0/05/Pieter_Bruegel_the_Elder-_The_Harvesters_-_Google_Art_Project.jpg",
  },
  {
    title: "The Arnolfini Portrait",
    author: AuthorsEnum.EYCK,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/640px-Van_Eyck_-_Arnolfini_Portrait.jpg",
  },
  {
    title: "The Garden of Earthly Delights",
    author: AuthorsEnum.BOSCH,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg/640px-The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg",
  },
  {
    title: "The Creation Of Adam",
    author: AuthorsEnum.MICHELANGELO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Creation_of_Adam%2C_Michelangelo_%281475%E2%80%931564%29%2C_circa_1511.jpg/640px-Creation_of_Adam%2C_Michelangelo_%281475%E2%80%931564%29%2C_circa_1511.jpg",
  },
  {
    title: "Nude Descending a Staircase, No. 2",
    author: AuthorsEnum.DUCHAMP,
    artmovement: ArtmovementsEnum.CUBISM,
    link: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Duchamp_-_Nude_Descending_a_Staircase.jpg/200px-Duchamp_-_Nude_Descending_a_Staircase.jpg",
  },
  {
    title: "Grande Odalisque",
    author: AuthorsEnum.INGRES,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/France-003335_-_Grande_Odalisque_%2816051027150%29.jpg/640px-France-003335_-_Grande_Odalisque_%2816051027150%29.jpg",
  },
  {
    title: "Wanderer above the Sea of Fog",
    author: AuthorsEnum.FRIEDRICH,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/640px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
  },
  {
    title: "The Swing",
    author: AuthorsEnum.FRAGONARD,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Fragonard%2C_The_Swing-detail_voyeur.jpg/640px-Fragonard%2C_The_Swing-detail_voyeur.jpg",
  },
  {
    title: "A Cotton Office In New Orleans",
    author: AuthorsEnum.DEGAS,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cottonexchange1873-Degas.jpg/640px-Cottonexchange1873-Degas.jpg",
  },
  {
    title: "Irises",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Irises-Vincent_van_Gogh.jpg/640px-Irises-Vincent_van_Gogh.jpg",
  },
  {
    title: "A Bar at the Folies-Bergère",
    author: AuthorsEnum.MANET,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Edouard_Manet%2C_A_Bar_at_the_Folies-Berg%C3%A8re.jpg/640px-Edouard_Manet%2C_A_Bar_at_the_Folies-Berg%C3%A8re.jpg",
  },
  {
    title: "The Scream",
    author: AuthorsEnum.MUNCH,
    artmovement: ArtmovementsEnum.EXPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Edvard_Munch_-_The_Scream_-_Google_Art_Project.jpg/640px-Edvard_Munch_-_The_Scream_-_Google_Art_Project.jpg",
  },
  {
    title: "Paris Street In Rainy Weather",
    author: AuthorsEnum.CAILLEBOTTE,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Gustave_Caillebotte_-_Paris_Street%3B_Rainy_Day_-_Google_Art_Project.jpg/640px-Gustave_Caillebotte_-_Paris_Street%3B_Rainy_Day_-_Google_Art_Project.jpg",
  },
  {
    title: "Boreas",
    author: AuthorsEnum.WATERHOUSE,
    artmovement: ArtmovementsEnum.PRE_RAPHAELITE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Boreas.jpg/640px-Boreas.jpg",
  },
  {
    title: "Branches with Almond Blossom",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Vincent_van_Gogh_-_Almond_blossom_-_Google_Art_Project.jpg/640px-Vincent_van_Gogh_-_Almond_blossom_-_Google_Art_Project.jpg",
  },
  {
    title: "Lady Godiva",
    author: AuthorsEnum.COLLIER,
    artmovement: ArtmovementsEnum.PRE_RAPHAELITE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Lady_Godiva_%28John_Collier%2C_c._1897%29.jpg/640px-Lady_Godiva_%28John_Collier%2C_c._1897%29.jpg",
  },
  {
    title: "Salvator Mundi",
    author: AuthorsEnum.LEONARDO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Leonardo_da_Vinci%2C_Salvator_Mundi%2C_c.1500%2C_oil_on_walnut%2C_45.4_%C3%97_65.6_cm.jpg/640px-Leonardo_da_Vinci%2C_Salvator_Mundi%2C_c.1500%2C_oil_on_walnut%2C_45.4_%C3%97_65.6_cm.jpg",
  },
  {
    title: "Among the Ruins",
    author: AuthorsEnum.ALMA_TADEMA,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://uploads3.wikiart.org/images/alma-tadema-lawrence/among-the-ruins-1904.jpg!Large.jpg",
  },
  {
    title: "Stag Night At Sharkeys",
    author: AuthorsEnum.BELLOWS,
    artmovement: ArtmovementsEnum.REALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/1909_Stag_at_Sharkey%27s.jpg/640px-1909_Stag_at_Sharkey%27s.jpg",
  },
  {
    title: "The Great Wave Off Kanagawa",
    author: AuthorsEnum.HOKUSAI,
    artmovement: ArtmovementsEnum.UKIYO_E,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Great_Wave_off_Kanagawa2.jpg/640px-Great_Wave_off_Kanagawa2.jpg",
  },
  {
    title: "Wheat Field with Cypresses",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Wheat-Field-with-Cypresses-%281889%29-Vincent-van-Gogh-Met.jpg/640px-Wheat-Field-with-Cypresses-%281889%29-Vincent-van-Gogh-Met.jpg",
  },
  {
    title: "A Friend In Need",
    author: AuthorsEnum.COOLIDGE,
    artmovement: ArtmovementsEnum.KITSCH,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/A_Friend_in_Need_1903_C.M.Coolidge.jpg/640px-A_Friend_in_Need_1903_C.M.Coolidge.jpg",
  },
  {
    title: "Boulevard des Capucines",
    author: AuthorsEnum.MONET,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Claude_Monet_-_Boulevard_des_Capucines_-_Google_Art_Project.jpg/640px-Claude_Monet_-_Boulevard_des_Capucines_-_Google_Art_Project.jpg",
  },
  {
    title: "Dancers Bending Down",
    author: AuthorsEnum.DEGAS,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://uploads8.wikiart.org/images/edgar-degas/dancers-bending-down-1885.jpg!Large.jpg",
  },
  {
    title: "Dante And Virgil In Hell",
    author: AuthorsEnum.BOUGUEREAU,
    artmovement: ArtmovementsEnum.REALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/William-Adolphe_Bouguereau_%281825-1905%29_-_Dante_And_Virgil_In_Hell_%281850%29.jpg/640px-William-Adolphe_Bouguereau_%281825-1905%29_-_Dante_And_Virgil_In_Hell_%281850%29.jpg",
  },
  {
    title: "When Will You Marry?",
    author: AuthorsEnum.GAUGUIN,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Paul_Gauguin%2C_Nafea_Faa_Ipoipo%3F_1892%2C_oil_on_canvas%2C_101_x_77_cm.jpg/640px-Paul_Gauguin%2C_Nafea_Faa_Ipoipo%3F_1892%2C_oil_on_canvas%2C_101_x_77_cm.jpg",
  },
  {
    title: "The Oath Of Horatii",
    author: AuthorsEnum.DAVID,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Jacques-Louis_David_-_Oath_of_the_Horatii_-_Google_Art_Project.jpg/640px-Jacques-Louis_David_-_Oath_of_the_Horatii_-_Google_Art_Project.jpg",
  },
  {
    title: "Flaming June",
    author: AuthorsEnum.LEIGHTON,
    artmovement: ArtmovementsEnum.PRE_RAPHAELITE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Flaming_June%2C_by_Frederic_Lord_Leighton_%281830-1896%29.jpg/640px-Flaming_June%2C_by_Frederic_Lord_Leighton_%281830-1896%29.jpg",
  },
  {
    title: "Annunciation",
    author: AuthorsEnum.LEONARDO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Leonardo_da_Vinci_-_Annunciation_-_WGA12677.jpg/640px-Leonardo_da_Vinci_-_Annunciation_-_WGA12677.jpg",
  },
  {
    title: "Dance at Bougival",
    author: AuthorsEnum.RENOIR,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://cdn.shopify.com/s/files/1/1771/4067/files/Dance_at_Bougival_by_Pierre_Auguste_Renoir_large.jpg?v=1571717117",
  },
  {
    title: "The Lady Of Shalott",
    author: AuthorsEnum.WATERHOUSE,
    artmovement: ArtmovementsEnum.PRE_RAPHAELITE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project.jpg/640px-John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project.jpg",
  },
  {
    title: "The Boating Party",
    author: AuthorsEnum.CASSATT,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Mary_Cassatt_-_The_Boating_Party_-_Google_Art_Project.jpg/270px-Mary_Cassatt_-_The_Boating_Party_-_Google_Art_Project.jpg",
  },
  {
    title: "Boulevard Montmartre Spring",
    author: AuthorsEnum.PISSARRO,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Camille_Pissarro_-_Boulevard_Montmartre%2C_Spring_-_Google_Art_Project.jpg/640px-Camille_Pissarro_-_Boulevard_Montmartre%2C_Spring_-_Google_Art_Project.jpg",
  },
  {
    title: "Sailboat at Le Petit-Gennevilliers",
    author: AuthorsEnum.MONET,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Claude_Monet_-_Boats_Moored_at_Le_Petit-Gennevilliers%2C_1874.jpg/640px-Claude_Monet_-_Boats_Moored_at_Le_Petit-Gennevilliers%2C_1874.jpg",
  },
  {
    title: "Nu couché",
    author: AuthorsEnum.MODIGLIANI,
    artmovement: ArtmovementsEnum.FAUVISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Modigliani_-_Nu_couch%C3%A9.jpg/640px-Modigliani_-_Nu_couch%C3%A9.jpg",
  },
  {
    title: "The Night Cafe",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Vincent_Willem_van_Gogh_076.jpg/300px-Vincent_Willem_van_Gogh_076.jpg",
  },
  {
    title: "The Woman with a Parasol",
    author: AuthorsEnum.MONET,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg/640px-Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg",
  },
  {
    title: "A Moorish Bath",
    author: AuthorsEnum.GEROME,
    artmovement: ArtmovementsEnum.ACADEMICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Jean-L%C3%A9on_G%C3%A9r%C3%B4me_-_Moorish_Bath_-_66.280_-_Rhode_Island_School_of_Design_Museum.jpg/640px-Jean-L%C3%A9on_G%C3%A9r%C3%B4me_-_Moorish_Bath_-_66.280_-_Rhode_Island_School_of_Design_Museum.jpg",
  },
  {
    title: "Portrait of Madame de Florian",
    author: AuthorsEnum.BOLDINI,
    artmovement: ArtmovementsEnum.MACCHIAIOLI,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Giovanni_Boldini_-_Portrait_de_madame_de_Florian.jpg/640px-Giovanni_Boldini_-_Portrait_de_madame_de_Florian.jpg",
  },
  {
    title: "The Beach at Trouville",
    author: AuthorsEnum.MONET,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://uploads6.wikiart.org/images/claude-monet/the-beach-at-trouville.jpg!Large.jpg",
  },
  {
    title: "The Magic Circle",
    author: AuthorsEnum.WATERHOUSE,
    artmovement: ArtmovementsEnum.PRE_RAPHAELITE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/John_William_Waterhouse_-_The_Magic_Circle_%28study%29.jpg/640px-John_William_Waterhouse_-_The_Magic_Circle_%28study%29.jpg",
  },
  {
    title: "The Hireling Shepherd",
    author: AuthorsEnum.HUNT,
    artmovement: ArtmovementsEnum.PRE_RAPHAELITE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/William_Holman_Hunt_001.jpg/640px-William_Holman_Hunt_001.jpg",
  },
  {
    title: "The Tower Of Babel",
    author: AuthorsEnum.BRUEGHEL_ELDER,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Brueghel-tower-of-babel.jpg/640px-Brueghel-tower-of-babel.jpg",
  },
  {
    title: "The Gleaners",
    author: AuthorsEnum.MILLET,
    artmovement: ArtmovementsEnum.REALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jean-Fran%C3%A7ois_Millet_-_Gleaners_-_Google_Art_Project_2.jpg/640px-Jean-Fran%C3%A7ois_Millet_-_Gleaners_-_Google_Art_Project_2.jpg",
  },
  {
    title: "The Card Players",
    author: AuthorsEnum.CEZANNE,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cezanne_The_Card_Players_Metmuseum.jpg/640px-Cezanne_The_Card_Players_Metmuseum.jpg",
  },
  {
    title: "A Wooded Path In Autumn",
    author: AuthorsEnum.BRENDEKILDE,
    artmovement: ArtmovementsEnum.SOCIAL_REALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/H._A._Brendekilde_-_A_wooded_path_in_autumn_%281902%29.jpg/640px-H._A._Brendekilde_-_A_wooded_path_in_autumn_%281902%29.jpg",
  },
  {
    title: "Spanish Dancer",
    author: AuthorsEnum.SARGENT,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Sargent_John_Singer_Spanish_Dancer.jpg/640px-Sargent_John_Singer_Spanish_Dancer.jpg",
  },
  {
    title: "A Mermaid",
    author: AuthorsEnum.WATERHOUSE,
    artmovement: ArtmovementsEnum.PRE_RAPHAELITE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Waterhouse_a_mermaid.jpg/640px-Waterhouse_a_mermaid.jpg",
  },
  {
    title: "The Orange Trees",
    author: AuthorsEnum.CAILLEBOTTE,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/G._Caillebotte_-_Les_orangers.jpg/640px-G._Caillebotte_-_Les_orangers.jpg",
  },
  {
    title: "The Siesta",
    author: AuthorsEnum.GAUGUIN,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/1893_Gauguin_Siesta_anagoria.JPG/640px-1893_Gauguin_Siesta_anagoria.JPG",
  },
  {
    title: "The Birth of Venus",
    author: AuthorsEnum.CABANEL,
    artmovement: ArtmovementsEnum.ACADEMICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Alexandre_Cabanel_-_The_Birth_of_Venus_-_Google_Art_Project_2.jpg/640px-Alexandre_Cabanel_-_The_Birth_of_Venus_-_Google_Art_Project_2.jpg",
  },
  {
    title: "Dance Class",
    author: AuthorsEnum.DEGAS,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/The_Dance_Class_A33234.jpg/640px-The_Dance_Class_A33234.jpg",
  },
  {
    title: "The Kiss",
    author: AuthorsEnum.HAYEZ,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Hayez_-_The_Kiss%2C_1859%2C_6335.jpg/640px-Hayez_-_The_Kiss%2C_1859%2C_6335.jpg",
  },
  {
    title: "Echo and Narcissus",
    author: AuthorsEnum.WATERHOUSE,
    artmovement: ArtmovementsEnum.PRE_RAPHAELITE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/John_William_Waterhouse_-_Echo_and_Narcissus_-_Google_Art_Project.jpg/640px-John_William_Waterhouse_-_Echo_and_Narcissus_-_Google_Art_Project.jpg",
  },
  {
    title: "Oarsmen",
    author: AuthorsEnum.CAILLEBOTTE,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/G._Caillebotte_-_Canotiers_ramant_sur_l%27Yerres.jpg/640px-G._Caillebotte_-_Canotiers_ramant_sur_l%27Yerres.jpg",
  },
  {
    title: "The Abduction of Psyche",
    author: AuthorsEnum.BOUGUEREAU,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Eros_and_Psyche_Eros_y_Psique_%28Cupido%29_PsycheabductFXD.jpg/640px-Eros_and_Psyche_Eros_y_Psique_%28Cupido%29_PsycheabductFXD.jpg",
  },
  {
    title: "Patroclus",
    author: AuthorsEnum.DAVID,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Jacques-Louis_David_-_Patroclus_-_WGA06044.jpg/640px-Jacques-Louis_David_-_Patroclus_-_WGA06044.jpg",
  },
  {
    title: "Head of a Woman",
    author: AuthorsEnum.LEONARDO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Leonardo_da_vinci%2C_Female_Head.jpg/640px-Leonardo_da_vinci%2C_Female_Head.jpg",
  },
  {
    title: "The Floor Scrapers",
    author: AuthorsEnum.CAILLEBOTTE,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Gustave_Caillebotte_-_Les_raboteurs_de_parquet_%28%C3%A9tude%29.jpg/640px-Gustave_Caillebotte_-_Les_raboteurs_de_parquet_%28%C3%A9tude%29.jpg",
  },
  {
    title: "Les Demoiselles d’Avignon",
    author: AuthorsEnum.PICASSO,
    artmovement: ArtmovementsEnum.CUBISM,
    link: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Les_Demoiselles_d%27Avignon.jpg/300px-Les_Demoiselles_d%27Avignon.jpg",
  },
  {
    title: "Composition with Red Blue and Yellow",
    author: AuthorsEnum.MONDRIAN,
    artmovement: ArtmovementsEnum.ABSTRACT_ART,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Piet_Mondriaan%2C_1930_-_Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg/640px-Piet_Mondriaan%2C_1930_-_Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg",
  },
  {
    title: "The Naked Maja",
    author: AuthorsEnum.GOYA,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Goya_Maja_naga2.jpg/640px-Goya_Maja_naga2.jpg",
  },
  {
    title: "The Japanese Footbridge And The Water Lily Pool",
    author: AuthorsEnum.MONET,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Japanese_Footbridge-Claude_Monet.jpg/640px-Japanese_Footbridge-Claude_Monet.jpg",
  },
  {
    title: "The Astronomer",
    author: AuthorsEnum.VERMEER,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Johannes_Vermeer_-_The_Astronomer_-_1668.jpg/640px-Johannes_Vermeer_-_The_Astronomer_-_1668.jpg",
  },
  {
    title: "The Persistence Of Memory",
    author: AuthorsEnum.DALI,
    artmovement: ArtmovementsEnum.SURREALISM,
    link: "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/The_Persistence_of_Memory.jpg/300px-The_Persistence_of_Memory.jpg",
  },
  {
    title: "Water Lilies",
    author: AuthorsEnum.MONET,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Monet_w1897.jpg/640px-Monet_w1897.jpg",
  },
  {
    title: "Judith Beheading Holofernes",
    author: AuthorsEnum.GENTILESCHI,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Artemisia_Gentileschi_-_Judith_Beheading_Holofernes_-_WGA8563.jpg/640px-Artemisia_Gentileschi_-_Judith_Beheading_Holofernes_-_WGA8563.jpg",
  },
  {
    title: "Moonrise Over The Sea",
    author: AuthorsEnum.FRIEDRICH,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Caspar_David_Friedrich_-_Mondaufgang_am_Meer_-_Google_Art_Project.jpg/640px-Caspar_David_Friedrich_-_Mondaufgang_am_Meer_-_Google_Art_Project.jpg",
  },
  {
    title: "Judith And Her Maidservant",
    author: AuthorsEnum.GENTILESCHI,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Artemisia_Gentileschi_-_Judith_and_Her_Maidservant_with_the_Head_of_Holofernes_-_52.253_-_Detroit_Institute_of_Arts.jpg/640px-Artemisia_Gentileschi_-_Judith_and_Her_Maidservant_with_the_Head_of_Holofernes_-_52.253_-_Detroit_Institute_of_Arts.jpg",
  },
  {
    title: "Bouquet Of Flowers",
    author: AuthorsEnum.BOSSCHAERT,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Ambrosius_Bosschaert_%28I%29_-_Bouquet_of_Flowers_-_WGA02652.jpg/640px-Ambrosius_Bosschaert_%28I%29_-_Bouquet_of_Flowers_-_WGA02652.jpg",
  },
  {
    title: "Young Hare",
    author: AuthorsEnum.DURER,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Albrecht_D%C3%BCrer_-_Hare%2C_1502_-_Google_Art_Project.jpg/640px-Albrecht_D%C3%BCrer_-_Hare%2C_1502_-_Google_Art_Project.jpg",
  },
  {
    title: "Paradise",
    author: AuthorsEnum.BRUEGHEL_YOUNGER,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Jan_Brueghel_the_Younger_Paradise.jpg/640px-Jan_Brueghel_the_Younger_Paradise.jpg",
  },
  {
    title: "Chalk Cliffs On Rügen",
    author: AuthorsEnum.FRIEDRICH,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Caspar_David_Friedrich%27s_Chalk_Cliffs_on_R%C3%BCgen.jpg/640px-Caspar_David_Friedrich%27s_Chalk_Cliffs_on_R%C3%BCgen.jpg",
  },
  {
    title: "Primavera",
    author: AuthorsEnum.BOTTICELLI,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Botticelli-primavera.jpg/1200px-Botticelli-primavera.jpg",
  },
  {
    title: "In A Roman Osteria",
    author: AuthorsEnum.BLOCH,
    artmovement: ArtmovementsEnum.ACADEMICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Carl_Bloch_-_In_a_Roman_Osteria_-_Google_Art_Project.jpg/640px-Carl_Bloch_-_In_a_Roman_Osteria_-_Google_Art_Project.jpg",
  },
  {
    title: "Little Girl In Blue Armchair",
    author: AuthorsEnum.CASSATT,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Cassatt_Mary_Little_Girl_in_a_Blue_Armchair_%281878%29.jpg/640px-Cassatt_Mary_Little_Girl_in_a_Blue_Armchair_%281878%29.jpg",
  },
  {
    title: "Portrait Of Madame X",
    author: AuthorsEnum.SARGENT,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Madame_X_%28Madame_Pierre_Gautreau%29%2C_John_Singer_Sargent%2C_1884_%28unfree_frame_crop%29.jpg/640px-Madame_X_%28Madame_Pierre_Gautreau%29%2C_John_Singer_Sargent%2C_1884_%28unfree_frame_crop%29.jpg",
  },
  {
    title: "At Eternity's Gate",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/1890-05_van_Gogh_At_Eternitys_Gate_anagoria.jpg/640px-1890-05_van_Gogh_At_Eternitys_Gate_anagoria.jpg",
  },
  {
    title: "The Blue Boy",
    author: AuthorsEnum.GAINSBOROUGH,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Thomas_Gainsborough_-_The_Blue_Boy_%28c._1770%29.jpg/640px-Thomas_Gainsborough_-_The_Blue_Boy_%28c._1770%29.jpg",
  },
  {
    title: "Vase With Fifteen Sunflowers",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Van_Gogh_Vase_with_Fifteen_Sunflowers.jpg/640px-Van_Gogh_Vase_with_Fifteen_Sunflowers.jpg",
  },
  {
    title: "Breezing Up",
    author: AuthorsEnum.HOMER,
    artmovement: ArtmovementsEnum.REALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Winslow_Homer_-_Breezing_Up_%28A_Fair_Wind%29_-_Google_Art_Project.jpg/640px-Winslow_Homer_-_Breezing_Up_%28A_Fair_Wind%29_-_Google_Art_Project.jpg",
  },
  {
    title: "The Gulf Stream",
    author: AuthorsEnum.HOMER,
    artmovement: ArtmovementsEnum.REALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Winslow_Homer_-_The_Gulf_Stream_-_Metropolitan_Museum_of_Art.jpg/640px-Winslow_Homer_-_The_Gulf_Stream_-_Metropolitan_Museum_of_Art.jpg",
  },
  {
    title: "Pink And Blue",
    author: AuthorsEnum.RENOIR,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Renoir_-_pink-and-blue-1881.jpg%21PinterestLarge.jpg/640px-Renoir_-_pink-and-blue-1881.jpg%21PinterestLarge.jpg",
  },
  {
    title: "Adele Bloch-Bauer II",
    author: AuthorsEnum.KLIMT,
    artmovement: ArtmovementsEnum.ART_NOUVEAU,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Gustav_Klimt_-_Portr%C3%A4t_der_Adele_Bloch-Bauer_I_%281907%29.jpg/640px-Gustav_Klimt_-_Portr%C3%A4t_der_Adele_Bloch-Bauer_I_%281907%29.jpg",
  },
  {
    title: "Laughing Cavalier",
    author: AuthorsEnum.HALS,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Cavalier_soldier_Hals-1624x.jpg/640px-Cavalier_soldier_Hals-1624x.jpg",
  },
  {
    title: "A Meadow In The Mountains",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/A_Meadow_in_the_Mountains_-_Le_Mas_de_Saint-Paul.jpg/640px-A_Meadow_in_the_Mountains_-_Le_Mas_de_Saint-Paul.jpg",
  },
  {
    title: "Pollice Verso",
    author: AuthorsEnum.GEROME,
    artmovement: ArtmovementsEnum.ACADEMICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Jean-Leon_Gerome_Pollice_Verso_%28cropped3%29.jpg/640px-Jean-Leon_Gerome_Pollice_Verso_%28cropped3%29.jpg",
  },
  {
    title: "Wapping",
    author: AuthorsEnum.WHISTLER,
    artmovement: ArtmovementsEnum.TONALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Whistler_Wapping.png/640px-Whistler_Wapping.png",
  },
  {
    title: "España Y Filipinas",
    author: AuthorsEnum.LUNA,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Espana_y_Filipinas_by_Juan_Luna.jpg/640px-Espana_y_Filipinas_by_Juan_Luna.jpg",
  },
  {
    title: "Serenade",
    author: AuthorsEnum.LEYSTER,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Judith_Leyster_-_Serenade_-_WGA12960.jpg/640px-Judith_Leyster_-_Serenade_-_WGA12960.jpg",
  },
  {
    title: "The Horse Fair",
    author: AuthorsEnum.BONHEUR,
    artmovement: ArtmovementsEnum.REALISM,
    link: "https://uploads8.wikiart.org/00381/images/rosa-bonheur/5-the-horse-fair-rosa-bonheur.jpg!Large.jpg",
  },
  {
    title: "The Red Roofs, A Corner Of A Village, Winter Effect",
    author: AuthorsEnum.PISSARRO,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Camille_Pissarro_-_Red_roofs%2C_corner_of_a_village%2C_winter_-_Google_Art_Project.jpg/640px-Camille_Pissarro_-_Red_roofs%2C_corner_of_a_village%2C_winter_-_Google_Art_Project.jpg",
  },
  {
    title: "Alexander Von Humboldt",
    author: AuthorsEnum.WEITSCH,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Alexander_von_Humboldt%2C_by_Friedrich_Georg_Weitsch.jpg/640px-Alexander_von_Humboldt%2C_by_Friedrich_Georg_Weitsch.jpg",
  },
  {
    title: "Netherlandish Proverbs",
    author: AuthorsEnum.BRUEGHEL_ELDER,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Pieter_Brueghel_the_Elder_-_The_Dutch_Proverbs_-_Google_Art_Project.jpg/640px-Pieter_Brueghel_the_Elder_-_The_Dutch_Proverbs_-_Google_Art_Project.jpg",
  },
  {
    title: "The Flagellation Of Christ",
    author: AuthorsEnum.CARAVAGGIO,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/The_Flagellation_of_Christ-Caravaggio_%281607%29.jpg/640px-The_Flagellation_of_Christ-Caravaggio_%281607%29.jpg",
  },
  {
    title: "By The Seashore",
    author: AuthorsEnum.RENOIR,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Renoir_-_by-the-seashore-1883.jpg%21PinterestLarge.jpg/640px-Renoir_-_by-the-seashore-1883.jpg%21PinterestLarge.jpg",
  },
  {
    title: "Portrait Of Juan De Pareja",
    author: AuthorsEnum.VELASQUEZ,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Retrato_de_Juan_Pareja%2C_by_Diego_Vel%C3%A1zquez.jpg/640px-Retrato_de_Juan_Pareja%2C_by_Diego_Vel%C3%A1zquez.jpg",
  },
  {
    title: "Lansdowne Portrait",
    author: AuthorsEnum.STUART,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Gilbert_Stuart%2C_George_Washington_%28Lansdowne_portrait%2C_1796%29.jpg/640px-Gilbert_Stuart%2C_George_Washington_%28Lansdowne_portrait%2C_1796%29.jpg",
  },
  {
    title: "The Hangover",
    author: AuthorsEnum.LAUTREC,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/The_Hangover_%28Suzanne_Valadon%29%2C_by_Henri_de_Toulouse-Lautrec%2C_1887-1889%2C_oil_on_canvas_-_Fogg_Art_Museum%2C_Harvard_University_-_DSC00697.jpg/640px-The_Hangover_%28Suzanne_Valadon%29%2C_by_Henri_de_Toulouse-Lautrec%2C_1887-1889%2C_oil_on_canvas_-_Fogg_Art_Museum%2C_Harvard_University_-_DSC00697.jpg",
  },
  {
    title: "A Lane In The Public Park At Arles",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Van_Gogh_Entrance_to_the_Public_Park_in_Arles.jpg/640px-Van_Gogh_Entrance_to_the_Public_Park_in_Arles.jpg",
  },
  {
    title: "Nocturne",
    author: AuthorsEnum.WHISTLER,
    artmovement: ArtmovementsEnum.TONALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Whistler-Nocturne_in_black_and_gold.jpg/640px-Whistler-Nocturne_in_black_and_gold.jpg",
  },
  {
    title: "Pinkie",
    author: AuthorsEnum.LAWRENCE,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Pinkie_detailed.jpg/640px-Pinkie_detailed.jpg",
  },
  {
    title: "The Proposition",
    author: AuthorsEnum.LEYSTER,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Judith_Leyster_-_Man_Offering_Money_to_a_Young_Woman_-_564_-_Mauritshuis.jpg/640px-Judith_Leyster_-_Man_Offering_Money_to_a_Young_Woman_-_564_-_Mauritshuis.jpg",
  },
  {
    title: "Paul Revere",
    author: AuthorsEnum.COPLEY,
    artmovement: ArtmovementsEnum.REALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/J_S_Copley_-_Paul_Revere_%28cropped%29.jpg/640px-J_S_Copley_-_Paul_Revere_%28cropped%29.jpg",
  },
  {
    title: "Composition VIII",
    author: AuthorsEnum.KANDINSKY,
    artmovement: ArtmovementsEnum.MODERN,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Vassily_Kandinsky%2C_1923_-_Composition_8%2C_huile_sur_toile%2C_140_cm_x_201_cm%2C_Mus%C3%A9e_Guggenheim%2C_New_York.jpg/640px-Vassily_Kandinsky%2C_1923_-_Composition_8%2C_huile_sur_toile%2C_140_cm_x_201_cm%2C_Mus%C3%A9e_Guggenheim%2C_New_York.jpg",
  },
  {
    title: "The Entombment Of Christ",
    author: AuthorsEnum.CARAVAGGIO,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/The_Entombment_of_Christ-Caravaggio_%28c.1602-3%29.jpg/640px-The_Entombment_of_Christ-Caravaggio_%28c.1602-3%29.jpg",
  },
  {
    title: "The Death Of Marat",
    author: AuthorsEnum.DAVID,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Death_of_Marat_by_David.jpg/640px-Death_of_Marat_by_David.jpg",
  },
  {
    title: "The Bedroom",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Vincent_van_Gogh_-_Van_Gogh%27s_Bedroom_in_Arles_-_Google_Art_Project.jpg/640px-Vincent_van_Gogh_-_Van_Gogh%27s_Bedroom_in_Arles_-_Google_Art_Project.jpg",
  },
  {
    title: "Portrait Of Henry VIII",
    author: AuthorsEnum.HOLBEIN,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Holbein_henry8_full_length.jpg/640px-Holbein_henry8_full_length.jpg",
  },
  {
    title: "Portrait Of The Postman Joseph Roulin",
    author: AuthorsEnum.GOGH,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Vincent_van_Gogh_-_Portrait_de_Joseph_Roulin_-_Google_Art_Project.jpg/640px-Vincent_van_Gogh_-_Portrait_de_Joseph_Roulin_-_Google_Art_Project.jpg",
  },
  {
    title: "The Garden Of The Tuileries On A Winter Afternoon",
    author: AuthorsEnum.PISSARRO,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Camille_Pissarro%2C_The_Garden_of_the_Tuileries_on_a_Winter_Afternoon%2C_1899_N2.jpg/640px-Camille_Pissarro%2C_The_Garden_of_the_Tuileries_on_a_Winter_Afternoon%2C_1899_N2.jpg",
  },
  {
    title: "Family Portrait",
    author: AuthorsEnum.ANGUISSOLA,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Sofonisba-Anguissola1.jpg/462px-Sofonisba-Anguissola1.jpg?20131231134804",
  },
  {
    title: "Flora",
    author: AuthorsEnum.REMBRANDT,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Harmensz_van_Rijn_Rembrandt_-_%D0%A4%D0%BB%D0%BE%D1%80%D0%B0_-_Google_Art_Project.jpg/640px-Harmensz_van_Rijn_Rembrandt_-_%D0%A4%D0%BB%D0%BE%D1%80%D0%B0_-_Google_Art_Project.jpg",
  },
  {
    title: "Tiger",
    author: AuthorsEnum.MARC,
    artmovement: ArtmovementsEnum.CUBISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Franz_Marc_-_Tiger_-_G_13320_-_Lenbachhaus.jpg/640px-Franz_Marc_-_Tiger_-_G_13320_-_Lenbachhaus.jpg",
  },
  {
    title: "Lucretia",
    author: AuthorsEnum.REMBRANDT,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Rembrandt_van_Rijn_-_Lucretia_-_Google_Art_Project_%28nAHoI2KdSaLshA%29.jpg/640px-Rembrandt_van_Rijn_-_Lucretia_-_Google_Art_Project_%28nAHoI2KdSaLshA%29.jpg",
  },
  {
    title: "Robert Louis Stevenson",
    author: AuthorsEnum.SARGENT,
    artmovement: ArtmovementsEnum.IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/John_Singer_Sargent_-_Robert_Louis_Stevenson_and_His_Wife_-_2005.3_-_Crystal_Bridges_Museum_of_American_Art.jpg/640px-John_Singer_Sargent_-_Robert_Louis_Stevenson_and_His_Wife_-_2005.3_-_Crystal_Bridges_Museum_of_American_Art.jpg",
  },
  {
    title: "The Seed Of The Areoi",
    author: AuthorsEnum.GAUGUIN,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Paul_Gauguin_-_Te_aa_no_areois_-_Google_Art_Project.jpg/640px-Paul_Gauguin_-_Te_aa_no_areois_-_Google_Art_Project.jpg",
  },
  {
    title: "Charles Garnier",
    author: AuthorsEnum.BAUDRY,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Charles_Garnier_1868_by_Paul_Baudry_1828_1886_edit.jpg/640px-Charles_Garnier_1868_by_Paul_Baudry_1828_1886_edit.jpg",
  },
  {
    title: "Day Of The God",
    author: AuthorsEnum.GAUGUIN,
    artmovement: ArtmovementsEnum.POST_IMPRESSIONISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Paul_Gauguin_-_Mahana_no_atua_%28Day_of_the_God%29_-_1926.198_-_Art_Institute_of_Chicago.jpg/640px-Paul_Gauguin_-_Mahana_no_atua_%28Day_of_the_God%29_-_1926.198_-_Art_Institute_of_Chicago.jpg",
  },
  {
    title: "The Battle Of Alexander At Issus",
    author: AuthorsEnum.ALTDORFER,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Albrecht_Altdorfer_-_Schlacht_bei_Issus_%28Alte_Pinakothek%2C_M%C3%BCnchen%29.jpg/640px-Albrecht_Altdorfer_-_Schlacht_bei_Issus_%28Alte_Pinakothek%2C_M%C3%BCnchen%29.jpg",
  },
  {
    title: "Washington Crossing The Delaware",
    author: AuthorsEnum.LEUTZE,
    artmovement: ArtmovementsEnum.ROMANTICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Washington_Crossing_the_Delaware_by_Emanuel_Leutze%2C_MMA-NYC%2C_1851.jpg/640px-Washington_Crossing_the_Delaware_by_Emanuel_Leutze%2C_MMA-NYC%2C_1851.jpg",
  },
  {
    title: "Samson And Delilah",
    author: AuthorsEnum.RUBENS,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Samson_and_Delilah_by_Rubens.jpg/640px-Samson_and_Delilah_by_Rubens.jpg",
  },
  {
    title: "Napoleon I On His Imperial Throne",
    author: AuthorsEnum.INGRES,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Ingres%2C_Napoleon_on_his_Imperial_throne.jpg/640px-Ingres%2C_Napoleon_on_his_Imperial_throne.jpg",
  },
  {
    title: "Las Damas Romanas",
    author: AuthorsEnum.LUNA,
    artmovement: ArtmovementsEnum.REALISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Luna_damas-romanas.jpg/640px-Luna_damas-romanas.jpg",
  },
  {
    title: "Christ Pantocrator",
    author: "unknown",
    artmovement: ArtmovementsEnum.MEDIEVAL,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/CHRIST_PANTOCRATOR-SINAI%286th_Century%29.jpg/640px-CHRIST_PANTOCRATOR-SINAI%286th_Century%29.jpg",
  },
  {
    title: "Lamentation (The Mourning of Christ)",
    author: AuthorsEnum.BONDONE,
    artmovement: ArtmovementsEnum.GOTHIC,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Giotto_-_Scrovegni_-_-36-_-_Lamentation_%28The_Mourning_of_Christ%29_adj.jpg/640px-Giotto_-_Scrovegni_-_-36-_-_Lamentation_%28The_Mourning_of_Christ%29_adj.jpg",
  },
  {
    title: "Maestà",
    author: AuthorsEnum.BUONINSEGNA,
    artmovement: ArtmovementsEnum.MEDIEVAL,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Maest_0_duccio_1308-11_siena_duomo.jpg/640px-Maest_0_duccio_1308-11_siena_duomo.jpg",
  },
  {
    title: "Ognissanti Madonna",
    author: AuthorsEnum.BONDONE,
    artmovement: ArtmovementsEnum.GOTHIC,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Giotto%2C_1267_Around-1337_-_Maest%C3%A0_-_Google_Art_Project.jpg/640px-Giotto%2C_1267_Around-1337_-_Maest%C3%A0_-_Google_Art_Project.jpg",
  },
  {
    title: "Annunciation with St. Margaret and St. Ansanus",
    author: AuthorsEnum.MARTINI_MEMMI,
    artmovement: ArtmovementsEnum.MEDIEVAL,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Simone_Martini_-_The_Annunciation_and_Two_Saints_-_WGA21438.jpg/640px-Simone_Martini_-_The_Annunciation_and_Two_Saints_-_WGA21438.jpg",
  },
  {
    title: "The Allegory of Good Government",
    author: AuthorsEnum.LORENZETTI,
    artmovement: ArtmovementsEnum.MEDIEVAL,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Ambrogio_Lorenzetti_-_Allegory_of_Good_Government_-_Google_Art_Project.jpg/640px-Ambrogio_Lorenzetti_-_Allegory_of_Good_Government_-_Google_Art_Project.jpg",
  },
  {
    title: "Bad Government and the Effects of Bad Government on the City Life",
    author: AuthorsEnum.LORENZETTI,
    artmovement: ArtmovementsEnum.MEDIEVAL,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Ambrogio_Lorenzetti_-_Bad_Government_and_the_Effects_of_Bad_Government_on_the_City_Life_-_WGA13499.jpg/640px-Ambrogio_Lorenzetti_-_Bad_Government_and_the_Effects_of_Bad_Government_on_the_City_Life_-_WGA13499.jpg",
  },
  {
    title: "Crucifixion Altarpiece",
    author: AuthorsEnum.BROEDERLAM,
    artmovement: ArtmovementsEnum.MEDIEVAL,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Melchior_Broederlam_-_The_Dijon_Altarpiece_-_WGA03220.jpg/640px-Melchior_Broederlam_-_The_Dijon_Altarpiece_-_WGA03220.jpg",
  },
  {
    title: "Wilton Diptych",
    author: "unknown",
    artmovement: ArtmovementsEnum.MEDIEVAL,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Wilton_diptych.jpg/640px-Wilton_diptych.jpg",
  },
  {
    title: "The Trinity",
    author: AuthorsEnum.RUBLEV,
    artmovement: ArtmovementsEnum.MEDIEVAL,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Andrey_Rublev_-_%D0%A1%D0%B2._%D0%A2%D1%80%D0%BE%D0%B8%D1%86%D0%B0_-_Google_Art_Project.jpg/640px-Andrey_Rublev_-_%D0%A1%D0%B2._%D0%A2%D1%80%D0%BE%D0%B8%D1%86%D0%B0_-_Google_Art_Project.jpg",
  },
  {
    title: "Adoration of the Magi ",
    author: AuthorsEnum.FABRIANO,
    artmovement: ArtmovementsEnum.MEDIEVAL,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Gentile_da_fabriano%2C_adorazione_dei_magi.jpg/640px-Gentile_da_fabriano%2C_adorazione_dei_magi.jpg",
  },
  {
    title: "Maestà di Santa Trinita",
    author: AuthorsEnum.CIMABUE,
    artmovement: ArtmovementsEnum.GOTHIC,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Cimabue_-_Maest%C3%A0_di_Santa_Trinita_-_Google_Art_Project.jpg/640px-Cimabue_-_Maest%C3%A0_di_Santa_Trinita_-_Google_Art_Project.jpg",
  },
  {
    title: "The Rucellai Madonna",
    author: AuthorsEnum.BUONINSEGNA,
    artmovement: ArtmovementsEnum.GOTHIC,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Duccio_di_Buoninsegna_-_Rucellai_Madonna_%28detail%29_-_WGA06823.jpg/640px-Duccio_di_Buoninsegna_-_Rucellai_Madonna_%28detail%29_-_WGA06823.jpg",
  },
  {
    title: "Flight into Egypt",
    author: AuthorsEnum.BONDONE,
    artmovement: ArtmovementsEnum.GOTHIC,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Giotto_di_Bondone_-_No._20_Scenes_from_the_Life_of_Christ_-_4._Flight_into_Egypt_-_WGA09198.jpg/640px-Giotto_di_Bondone_-_No._20_Scenes_from_the_Life_of_Christ_-_4._Flight_into_Egypt_-_WGA09198.jpg",
  },
  {
    title: "Adoration of the Magi",
    author: AuthorsEnum.BONDONE,
    artmovement: ArtmovementsEnum.GOTHIC,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Giotto_-_Scrovegni_-_-18-_-_Adoration_of_the_Magi.jpg/640px-Giotto_-_Scrovegni_-_-18-_-_Adoration_of_the_Magi.jpg",
  },
  {
    title: "Madonna with Child",
    author: AuthorsEnum.CRIVELLI,
    artmovement: ArtmovementsEnum.GOTHIC,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Madonna_col_Bambino_Carlo_Crivelli_GAC.jpg/640px-Madonna_col_Bambino_Carlo_Crivelli_GAC.jpg",
  },
  {
    title: "Doni Tondo",
    author: AuthorsEnum.MICHELANGELO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Tondo_Doni%2C_por_Miguel_%C3%81ngel.jpg/640px-Tondo_Doni%2C_por_Miguel_%C3%81ngel.jpg",
  },
  {
    title: "Assumption of Virgin",
    author: AuthorsEnum.TITIAN,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Tiziani%2C_assunta_02.jpg/640px-Tiziani%2C_assunta_02.jpg",
  },
  {
    title: "Virgin of the Rocks",
    author: AuthorsEnum.LEONARDO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Leonardo_Da_Vinci_-_Vergine_delle_Rocce_%28Louvre%29.jpg/640px-Leonardo_Da_Vinci_-_Vergine_delle_Rocce_%28Louvre%29.jpg",
  },
  {
    title: "Diana and Actaeon",
    author: AuthorsEnum.TITIAN,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Titian_-_Diana_and_Actaeon_-_Google_Art_Project.jpg/640px-Titian_-_Diana_and_Actaeon_-_Google_Art_Project.jpg",
  },
  {
    title: "Venus of Urbino",
    author: AuthorsEnum.TITIAN,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Venus_de_Urbino%2C_por_Tiziano.jpg/640px-Venus_de_Urbino%2C_por_Tiziano.jpg",
  },
  {
    title: "Bacchus and Ariadne",
    author: AuthorsEnum.TITIAN,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Titian_Bacchus_and_Ariadne.jpg/640px-Titian_Bacchus_and_Ariadne.jpg",
  },
  {
    title: "The Sistine Madonna",
    author: AuthorsEnum.RAFAELLO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/RAFAEL_-_Madonna_Sixtina_%28Gem%C3%A4ldegalerie_Alter_Meister%2C_Dresden%2C_1513-14._%C3%93leo_sobre_lienzo%2C_265_x_196_cm%29.jpg/640px-RAFAEL_-_Madonna_Sixtina_%28Gem%C3%A4ldegalerie_Alter_Meister%2C_Dresden%2C_1513-14._%C3%93leo_sobre_lienzo%2C_265_x_196_cm%29.jpg",
  },
  {
    title: "The School of Athens",
    author: AuthorsEnum.RAFAELLO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/640px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg",
  },
  {
    title: "The Baptism of Christ",
    author: AuthorsEnum.VERROCCHIO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Andrea_del_Verrocchio%2C_Leonardo_da_Vinci_-_Baptism_of_Christ_-_Uffizi.jpg/640px-Andrea_del_Verrocchio%2C_Leonardo_da_Vinci_-_Baptism_of_Christ_-_Uffizi.jpg",
  },
  {
    title: "Flagellation of Christ",
    author: AuthorsEnum.FRANCESCA,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Piero%2C_flagellazione.jpg/640px-Piero%2C_flagellazione.jpg",
  },
  {
    title: "Lamentation of Christ",
    author: AuthorsEnum.MANTEGNA,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Andrea_Mantegna_-_The_Lamentation_over_the_Dead_Christ_-_WGA13981.jpg/640px-Andrea_Mantegna_-_The_Lamentation_over_the_Dead_Christ_-_WGA13981.jpg",
  },
  {
    title: "Adoration of the Magi",
    author: AuthorsEnum.LEONARDO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Leonardo_da_Vinci_-_Adoration_of_the_Magi_-_WGA12693.jpg/640px-Leonardo_da_Vinci_-_Adoration_of_the_Magi_-_WGA12693.jpg",
  },
  {
    title: "Portrait of a Man",
    author: AuthorsEnum.EYCK,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Portrait_of_a_Man_in_a_Turban_%28Jan_van_Eyck%29.jpg/640px-Portrait_of_a_Man_in_a_Turban_%28Jan_van_Eyck%29.jpg",
  },
  {
    title: "The Ambassadors",
    author: AuthorsEnum.HOLBEIN,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg/640px-Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg",
  },
  {
    title: "The Burial of the Count of Orgaz",
    author: AuthorsEnum.GRECO,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/El_Greco_-_The_Burial_of_the_Count_of_Orgaz.JPG/640px-El_Greco_-_The_Burial_of_the_Count_of_Orgaz.JPG",
  },
  {
    title: "The Wedding at Cana",
    author: AuthorsEnum.VERONESE,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Paolo_Veronese_008.jpg/640px-Paolo_Veronese_008.jpg",
  },
  {
    title: "Madonna with the Long Neck",
    author: AuthorsEnum.PARMIGIANINO,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Parmigianino_-_Madonna_dal_collo_lungo_-_Google_Art_Project.jpg/640px-Parmigianino_-_Madonna_dal_collo_lungo_-_Google_Art_Project.jpg",
  },
  {
    title: "Il Paradiso",
    author: AuthorsEnum.TINTORETTO,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/%28Venice%29_Jacopo_Tintoretto_-_Gloria_del_Paradiso_-_Sala_del_Maggior_Consiglio.jpg/640px-%28Venice%29_Jacopo_Tintoretto_-_Gloria_del_Paradiso_-_Sala_del_Maggior_Consiglio.jpg",
  },
  {
    title: "The Archdukes Albert and Isabella Visiting a Collector’s Cabinet",
    author: AuthorsEnum.BRUEGHEL_YOUNGER,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Hieronymus_Francken_Ii_-_The_Archdukes_Albert_and_Isabella_Visiting_a_Collector%27s_Cabinet_-_Google_Art_Project.jpg/640px-Hieronymus_Francken_Ii_-_The_Archdukes_Albert_and_Isabella_Visiting_a_Collector%27s_Cabinet_-_Google_Art_Project.jpg",
  },
  {
    title: "Portrait of Eleanor of Toledo",
    author: AuthorsEnum.BRONZINO,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Bronzino_-_Eleonora_di_Toledo_col_figlio_Giovanni_-_Google_Art_Project.jpg/640px-Bronzino_-_Eleonora_di_Toledo_col_figlio_Giovanni_-_Google_Art_Project.jpg",
  },
  {
    title: "The Feast in the House of Levi",
    author: AuthorsEnum.VERONESE,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/The_Feast_in_the_House_of_Levi_by_Paolo_Veronese_%28edited_2%29.jpg/640px-The_Feast_in_the_House_of_Levi_by_Paolo_Veronese_%28edited_2%29.jpg",
  },
  {
    title: "Miracle of the Slave",
    author: AuthorsEnum.TINTORETTO,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Accademia_-_Miracle_of_the_Slave_by_Tintoretto.jpg/640px-Accademia_-_Miracle_of_the_Slave_by_Tintoretto.jpg",
  },
  {
    title: "Opening of the Fifth Seal",
    author: AuthorsEnum.GRECO,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/The_Vision_of_Saint_John_MET_DT1052.jpg/640px-The_Vision_of_Saint_John_MET_DT1052.jpg",
  },
  {
    title: "Laocoön",
    author: AuthorsEnum.GRECO,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/El_Greco_%28Domenikos_Theotokopoulos%29_-_Laoco%C3%B6n_-_Google_Art_Project.jpg/640px-El_Greco_%28Domenikos_Theotokopoulos%29_-_Laoco%C3%B6n_-_Google_Art_Project.jpg",
  },
  {
    title: "Volterra Deposition",
    author: AuthorsEnum.FIORENTINO,
    artmovement: ArtmovementsEnum.MANNERISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Rosso_fiorentino%2C_deposizione%2C_1521_%28volterra%2C_pinacoteca_civica%29_01.jpg/640px-Rosso_fiorentino%2C_deposizione%2C_1521_%28volterra%2C_pinacoteca_civica%29_01.jpg",
  },
  {
    title: "The Calling of Saint Matthew",
    author: AuthorsEnum.CARAVAGGIO,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/The_Calling_of_Saint_Matthew-Caravaggo_%281599-1600%29.jpg/640px-The_Calling_of_Saint_Matthew-Caravaggo_%281599-1600%29.jpg",
  },
  {
    title: "Domine, quo vadis",
    author: AuthorsEnum.CARRACCI,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Domine%2C_quo_vadis.jpg/640px-Domine%2C_quo_vadis.jpg",
  },
  {
    title: "Venus and Cupid (Pontormo)",
    author: AuthorsEnum.MICHELANGELO,
    artmovement: ArtmovementsEnum.RENNAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Pontormo%2C_venere_e_amore_da_michelangelo%2C_1533_ca._01.jpg/640px-Pontormo%2C_venere_e_amore_da_michelangelo%2C_1533_ca._01.jpg",
  },
  {
    title: "Pilgrimage to Cythera",
    author: AuthorsEnum.WATTEAU,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/L%27Embarquement_pour_Cythere%2C_by_Antoine_Watteau%2C_from_C2RMF_retouched.jpg/640px-L%27Embarquement_pour_Cythere%2C_by_Antoine_Watteau%2C_from_C2RMF_retouched.jpg",
  },
  {
    title: "Triumph of Venus",
    author: AuthorsEnum.BOUCHER,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Fran%C3%A7ois_Boucher_-_The_Triumph_of_Venus_-_Google_Art_Project.jpg/640px-Fran%C3%A7ois_Boucher_-_The_Triumph_of_Venus_-_Google_Art_Project.jpg",
  },
  {
    title: "The Meeting",
    author: AuthorsEnum.FRAGONARD,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/The_Progress_of_Love_-_The_Meeting_-_Fragonard_1771-72.jpg/640px-The_Progress_of_Love_-_The_Meeting_-_Fragonard_1771-72.jpg",
  },
  {
    title: "Portrait of the Marquise de Pompadour",
    author: AuthorsEnum.LA_TOUR,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Maurice_Quentin_de_La_Tour_-_Marquise_de_Pompadour_-_WGA12359.jpg/640px-Maurice_Quentin_de_La_Tour_-_Marquise_de_Pompadour_-_WGA12359.jpg",
  },
  {
    title: "Charles III Dining Before the Court",
    author: AuthorsEnum.PARET_Y_ALCAZAR,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Luis_Paret_Y_Alcaz%C3%A1r_-_Charles_III_Dining_before_the_Court_-_WGA17017.jpg/640px-Luis_Paret_Y_Alcaz%C3%A1r_-_Charles_III_Dining_before_the_Court_-_WGA17017.jpg",
  },
  {
    title: "The Marriage of the Emperor Frederick and Beatrice of Burgundy",
    author: AuthorsEnum.TIEPOLO,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Hochzeit_friedrich_I._tiepolo.jpg/640px-Hochzeit_friedrich_I._tiepolo.jpg",
  },
  {
    title: "The Declaration of Love",
    author: AuthorsEnum.DE_TROY,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Declarationoflove.jpg/640px-Declarationoflove.jpg",
  },
  {
    title: "Marie Antoinette in a Court Dress",
    author: AuthorsEnum.VIGEE_LE_BRUN,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Marie_Antoinette_Adult.jpg/640px-Marie_Antoinette_Adult.jpg",
  },
  {
    title: "The Settlement",
    author: AuthorsEnum.HOGARTH,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/William_Hogarth_-_Marriage_A-la-Mode_1_The_Marriage_Settlement.jpg/640px-William_Hogarth_-_Marriage_A-la-Mode_1_The_Marriage_Settlement.jpg",
  },
  {
    title: "Portrait of Madame de Pompadour",
    author: AuthorsEnum.BOUCHER,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Madame_de_Pompadour_by_Fran%C3%A7ois_BoucherFXD.jpg/640px-Madame_de_Pompadour_by_Fran%C3%A7ois_BoucherFXD.jpg",
  },
  {
    title: "Hercules and Omphale",
    author: AuthorsEnum.LEMOYNE,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Fran%C3%A7ois_Lemoyne_-_Hercules_and_Omphale_-_WGA12655.jpg/640px-Fran%C3%A7ois_Lemoyne_-_Hercules_and_Omphale_-_WGA12655.jpg",
  },
  {
    title: "The Triumph of Venice",
    author: AuthorsEnum.BATONI,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Batoni%2C_Pompeo_-_The_Triumph_of_Venice_-_1737.jpg/640px-Batoni%2C_Pompeo_-_The_Triumph_of_Venice_-_1737.jpg",
  },
  {
    title: "Diana Leaving the Bath",
    author: AuthorsEnum.BOUCHER,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Fran%C3%A7ois_Boucher_-_Diana_Resting_after_her_Bath%2C_1742.jpg/640px-Fran%C3%A7ois_Boucher_-_Diana_Resting_after_her_Bath%2C_1742.jpg",
  },
  {
    title: "The Interrupted Sleep",
    author: AuthorsEnum.BOUCHER,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Fran%C3%A7ois_Boucher_-_The_Interrupted_Sleep_-_WGA2905.jpg/640px-Fran%C3%A7ois_Boucher_-_The_Interrupted_Sleep_-_WGA2905.jpg",
  },
  {
    title: "An Allegory with Venus and Time",
    author: AuthorsEnum.TIEPOLO,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/TIEPOLO_-_An_Allegory_with_Venus_and_Time.png/640px-TIEPOLO_-_An_Allegory_with_Venus_and_Time.png",
  },
  {
    title: "The Lock",
    author: AuthorsEnum.FRAGONARD,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Jean-Honor%C3%A9_Fragonard_-_The_Bolt_-_WGA8080.jpg/640px-Jean-Honor%C3%A9_Fragonard_-_The_Bolt_-_WGA8080.jpg",
  },
  {
    title: "Marie Antoinette with a Rose",
    author: AuthorsEnum.VIGEE_LE_BRUN,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Louise_Elisabeth_Vig%C3%A9e-Lebrun_-_Marie-Antoinette_dit_%C2%AB_%C3%A0_la_Rose_%C2%BB_-_Google_Art_Project.jpg/640px-Louise_Elisabeth_Vig%C3%A9e-Lebrun_-_Marie-Antoinette_dit_%C2%AB_%C3%A0_la_Rose_%C2%BB_-_Google_Art_Project.jpg",
  },
  {
    title: "Marie Antoinette and Her Children",
    author: AuthorsEnum.VIGEE_LE_BRUN,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Louise_Elisabeth_Vig%C3%A9e-Lebrun_-_Marie-Antoinette_de_Lorraine-Habsbourg%2C_reine_de_France_et_ses_enfants_-_Google_Art_Project.jpg/640px-Louise_Elisabeth_Vig%C3%A9e-Lebrun_-_Marie-Antoinette_de_Lorraine-Habsbourg%2C_reine_de_France_et_ses_enfants_-_Google_Art_Project.jpg",
  },
  {
    title: "Pierrot, formerly known as Gilles",
    author: AuthorsEnum.WATTEAU,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Jean-Antoine_Watteau_-_Pierrot%2C_dit_autrefois_Gilles.jpg/640px-Jean-Antoine_Watteau_-_Pierrot%2C_dit_autrefois_Gilles.jpg",
  },
  {
    title: "The Soap Bubbles",
    author: AuthorsEnum.CHARDIN,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Jean_Sim%C3%A9on_Chardin_-_Soap_Bubbles_-_Google_Art_Project.jpg/640px-Jean_Sim%C3%A9on_Chardin_-_Soap_Bubbles_-_Google_Art_Project.jpg",
  },
  {
    title: "Bouquet of flowers in a glass of water",
    author: AuthorsEnum.VALLAYER_COSTER,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Beaux-Arts_de_Carcassonne_-_Bouquet_de_fleurs_dans_un_verre_d%27eau_-_Anne_Vallayer-Coster_-_Joconde04400000408.jpg/640px-Beaux-Arts_de_Carcassonne_-_Bouquet_de_fleurs_dans_un_verre_d%27eau_-_Anne_Vallayer-Coster_-_Joconde04400000408.jpg",
  },
  {
    title: "Brown Odalisque",
    author: AuthorsEnum.BOUCHER,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Brown-Odalisque-1745.JPG/640px-Brown-Odalisque-1745.JPG",
  },
  {
    title: "The Bathing Pool",
    author: AuthorsEnum.ROBERT,
    artmovement: ArtmovementsEnum.ROCOCO,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Hubert_Robert_-_The_Bathing_Pool.jpg/640px-Hubert_Robert_-_The_Bathing_Pool.jpg",
  },
  {
    title: "Parnassus",
    author: AuthorsEnum.MENGS,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Parnassus%2C_by_Anton_Raphael_Mengs.jpg/640px-Parnassus%2C_by_Anton_Raphael_Mengs.jpg",
  },
  {
    title: "The Death of General Wolfe",
    author: AuthorsEnum.WEST,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Benjamin_West_005.jpg/640px-Benjamin_West_005.jpg",
  },
  {
    title: "King Lear Weeping over the Dead Body of Cordelia",
    author: AuthorsEnum.BARRY,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/James_Barry_%281741-1806%29_-_King_Lear_Weeping_over_the_Dead_Body_of_Cordelia_-_T00556_-_Tate.jpg/640px-James_Barry_%281741-1806%29_-_King_Lear_Weeping_over_the_Dead_Body_of_Cordelia_-_T00556_-_Tate.jpg",
  },
  {
    title: "Self-Portrait with Her Daughter",
    author: AuthorsEnum.VIGEE_LE_BRUN,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Self-portrait_with_Her_Daughter_by_Elisabeth-Louise_Vig%C3%A9e_Le_BrunFXD.jpg/640px-Self-portrait_with_Her_Daughter_by_Elisabeth-Louise_Vig%C3%A9e_Le_BrunFXD.jpg",
  },
  {
    title: "The Turkish Bath",
    author: AuthorsEnum.INGRES,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Le_Bain_Turc%2C_by_Jean_Auguste_Dominique_Ingres%2C_from_C2RMF_retouched.jpg/640px-Le_Bain_Turc%2C_by_Jean_Auguste_Dominique_Ingres%2C_from_C2RMF_retouched.jpg",
  },
  {
    title: "The Birth of Venus",
    author: AuthorsEnum.BOUGUEREAU,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/William-Adolphe_Bouguereau_%281825-1905%29_-_The_Birth_of_Venus_%281879%29.jpg/640px-William-Adolphe_Bouguereau_%281825-1905%29_-_The_Birth_of_Venus_%281879%29.jpg",
  },
  {
    title: "Mischief and Repose",
    author: AuthorsEnum.GODWARD,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Godward%2C_John_William_-_Mischief_and_Repose_-_Google_Art_Project.jpg/640px-Godward%2C_John_William_-_Mischief_and_Repose_-_Google_Art_Project.jpg",
  },
  {
    title: "Nymphs and Satyr",
    author: AuthorsEnum.BOUGUEREAU,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/William-Adolphe_Bouguereau_%281825-1905%29_-_Nymphs_and_Satyr_%281873%29_HQ.jpg/640px-William-Adolphe_Bouguereau_%281825-1905%29_-_Nymphs_and_Satyr_%281873%29_HQ.jpg",
  },
  {
    title: "The Death of Socrates",
    author: AuthorsEnum.DAVID,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/David_-_The_Death_of_Socrates.jpg/640px-David_-_The_Death_of_Socrates.jpg",
  },
  {
    title: "The Sorrow of Telemachus",
    author: AuthorsEnum.KAUFFMANN,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/The_Sorrow_of_Telemachus_MET_DP169392.jpg/640px-The_Sorrow_of_Telemachus_MET_DP169392.jpg",
  },
  {
    title: "The Intervention of the Sabine Women",
    author: AuthorsEnum.DAVID,
    artmovement: ArtmovementsEnum.NEOCLASSICISM,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/F0440_Louvre_JL_David_Sabines_INV3691_rwk.jpg/640px-F0440_Louvre_JL_David_Sabines_INV3691_rwk.jpg",
  },
  {
    title: "Ophelia",
    author: AuthorsEnum.MILLAIS,
    artmovement: ArtmovementsEnum.PRE_RAPHAELITE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg/640px-John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg",
  },
  {
    title: "Melancholia",
    author: AuthorsEnum.DURER,
    artmovement: ArtmovementsEnum.NORTHERN_RENAISSANCE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/D%C3%BCrer_Melancholia_I.jpg/640px-D%C3%BCrer_Melancholia_I.jpg",
  },
  {
    title: "Medusa",
    author: AuthorsEnum.CARAVAGGIO,
    artmovement: ArtmovementsEnum.BAROQUE,
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Caravaggio_-_Medusa_-_Google_Art_Project.jpg/640px-Caravaggio_-_Medusa_-_Google_Art_Project.jpg",
  },
];

export default ArtObject;
